language: node_js
node_js:
    - "0.12"
    - "iojs"
services:
    - redis-server
after_success:
    - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha test --report lcovonly -- --require babel/register -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
